import Head from "next/head";
import React, { useContext, useEffect, useState } from "react";
import AdminMessenger from "../components/AdminMessenger";
import Navbar from "../components/Navbar";
import { DataContext } from "../context/authContext";
import { getFromLocalStorage } from "../utils/browserStorage";
import Login from "./login";
const Home = () => {
  
  const {user}=useContext(DataContext)
  console.log(user)

  if(user){
    return(
      <div>
      <Head>
        <title>MessengerApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminMessenger />
    </div>
    )
  }
  return (
    <div>
      <Head>
        <title>MessengerApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login/>
    </div>
  );
};

export default Home;
