import Head from "next/head";
import React, { useContext, useEffect, useState } from "react";
import AdminMessenger from "../components/AdminMessenger";
import Navbar from "../components/Navbar";
import { DataContext } from "../context/authContext";
import Login from "./login";
const Home = () => {
  
  const {user}=useContext(DataContext)
  console.log(user)
  return (
    <div>
      <Head>
        <title>MessengerApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? <AdminMessenger />: <Login/>}
    </div>
  );
};

export default Home;
